package fpinscala.state

import org.scalatest._

class Exercise6_3Spec extends FlatSpec {

  // intDouble

  "int and double generated by intDouble" should "be the same" in {
    val rng = RNG.Simple(12345)
    val ((i1, d1), nextRng1) = RNG.intDouble(rng)
    val ((i2, d2), nextRng2) = RNG.intDouble(rng)
    assert(i1 == i2 && d1 == d2)
    assert(nextRng1 === nextRng2)
  }

  // doubleInt

  "double and int generated by doubleInt" should "be the same" in {
    val rng = RNG.Simple(12345)
    val ((d1, i1), nextRng1) = RNG.doubleInt(rng)
    val ((d2, i2), nextRng2) = RNG.doubleInt(rng)
    assert(d1 == d2 && i1 == i2)
    assert(nextRng1 === nextRng2)
  }

  // double3

  "doubles generated by double3" should "be the same" in {
    val rng = RNG.Simple(12345)
    val ((d1, d2, d3), nextRng1) = RNG.double3(rng)
    val ((dd1, dd2, dd3), nextRng2) = RNG.double3(rng)
    assert(d1 == dd1 && d2 == dd2 && d3 == dd3)
    assert(nextRng1 === nextRng2)
  }
}
