package fpinscala.state

import org.scalatest._

class Exercise6_4Spec extends FlatSpec {

  "int and double generated by intDouble" should "be the same" in {
    val rng = RNG.Simple(12345)
    val (integers1, nextRng1) = RNG.ints(4)(rng)
    val (integers2, nextRng2) = RNG.ints(4)(rng)
    assert(integers1.length === 4)
    assert(integers1 === integers2)
    assert(nextRng1 === nextRng2)
  }
}
