package fpinscala.state

import org.scalatest._

class Exercise6_1Spec extends FlatSpec {

  "value and nextRng generated by rng" should "be the same" in {
    val rng = RNG.Simple(1)
    val (n1, nextRng1) = RNG.nonNegativeInt(rng)
    val (n2, nextRng2) = RNG.nonNegativeInt(rng)
    assert(n1 === n2)
    assert(nextRng1 === nextRng2)
  }
}
