package fpinscala.state

import fpinscala.state.RNG.Rand
import org.scalatest._

class Exercise6_7Spec extends FlatSpec {

  "two rands" should "two integers" in {
    val func: Rand[List[Int]] = RNG.sequence(List(RNG.int, RNG.int))
    val rng = RNG.Simple(12345)
    val (l1, nextRng1) = func(rng)
    val (l2, nextRng2) = func(rng)

    assert(l1 == l2)
    assert(l1.length === 2)
    assert(nextRng1 === nextRng2)
  }

  "value and nextRng generated by rng" should "be the same" in {
    val func: Rand[List[Int]] = RNG.sequence(List(RNG.int, RNG.int, RNG.int))
    val rng = RNG.Simple(12345)
    val (l1, nextRng1) = func(rng)
    val (l2, nextRng2) = func(rng)

    assert(l1 == l2)
    assert(l1.length === 3)
    assert(nextRng1 === nextRng2)
  }
}
