package fpinscala.state

import org.scalatest._

class Exercise6_5Spec extends FlatSpec {

  "value and nextRng generated by rng" should "be the same" in {
    val rng = RNG.Simple(12345)
    val (n1, nextRng1) = RNG.doubleViaMap(rng)
    val (n2, nextRng2) = RNG.doubleViaMap(rng)
    assert(n1 >= 0 && n1 < 1)
    assert(n1 == n2)
    assert(nextRng1 === nextRng2)
  }
}
